export const TWEAK_DEFAULTS = {
  showAlerts: true,
  softMode: false,
  showTeams: true,
}

export const MEMBERS = [
  {
    id: 'gabriel',
    name: 'Gabriel Gutiérrez',
    initials: 'GB',
    nickname: '"Barry"',
    role: 'El Gatekeeper',
    roleShort: 'Admin',
    color: 'oklch(72% 0.18 60)',
    colorHex: '#c4850a',
    team: 'Real Madrid',
    activity: 8,
    warning: false,
    scores: [
      { label: 'Agresión', val: 4, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 7, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 8, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 6, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Admin que ejerce autoridad con silencios y expulsiones estratégicas',
      'Humor lacónico - dice mucho en pocas palabras',
      'Sale voluntariamente del grupo en oct 2025 por la toxicidad',
      'Sus análisis de política del fútbol son los más lúcidos del grupo',
    ],
    quotes: [
      { text: '"El circo es ir a jugar a la pelota."', ctx: 'Sobre Copa del Rey y política del fútbol, abr 2025' },
      { text: '"Desde que se fue Gustavo me quedé sin amigos. Todo es culpa de Gustavo."', ctx: 'Después de expulsarlo del grupo, con humor' },
      { text: '"¿Es en serio que estamos teniendo esta discusión? JAJAJAJA"', ctx: 'Reacción cuando Javier justificó llamar "mono" a Vinicius' },
    ],
    relations: [
      { who: 'Francisco', type: '🤝 Alianza', desc: 'Principal aliado. Debate con él en privado cuando el grupo escala.' },
      { who: 'Gustavo', type: '😂 Tensión cómica', desc: 'Lo expulsa y readmite en minutos. El grupo lo llama "Gabriel J. Trump".' },
      { who: 'Javier', type: '⚡ Autoridad', desc: 'Lo expulsó durante la final de Copa del Rey sin previo aviso.' },
      { who: 'Jesús', type: '🤫 Complicidad', desc: 'Silencio cómplice. Humor compartido sin palabras.' },
    ],
    arc: 'Consistente y medido. Más callado hacia dic 2025. Sale del grupo en octubre - regresa sin drama. Su mayor acto de juicio es reaccionar con incredulidad cuando Javier minimiza el racismo contra Vinicius.',
  },
  {
    id: 'francisco',
    name: 'Francisco Arteaga',
    initials: 'FA',
    nickname: '"Paquito"',
    role: 'El Motor del Grupo',
    roleShort: 'Motor',
    color: 'oklch(66% 0.22 32)',
    colorHex: '#d04820',
    team: 'Real Madrid',
    activity: 10,
    warning: false,
    scores: [
      { label: 'Agresión', val: 7, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 8, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 6, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 4, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Genera el 40%+ de los mensajes - el motor indiscutible del chat',
      'Argumenta con fuentes y datos, pero su frustración escala rápido',
      'Tiene newsletter propio, vive en Madrid - el más "dentro" del tema',
      'Sus temas favoritos: VAR, árbitros, política del fútbol, fichajes',
    ],
    quotes: [
      { text: '"Creer en el VAR es creer en Santa Claus."', ctx: 'Mayo 2025, debate VAR' },
      { text: '"Es difícil hablar con alguien que no entiende de fútbol o de la vida real."', ctx: 'A Javier, mayo 2025' },
      { text: '"Los quiero muchachos." - Antes de que su avión despegara.', ctx: 'Feb 2026, caso Prestiani - humor negro en momentos tensos' },
    ],
    relations: [
      { who: 'Gabriel', type: '🤝 Alianza', desc: 'Su árbitro personal cuando se pasa de la raya.' },
      { who: 'Gustavo', type: '⚡ Conflicto', desc: 'Sparring principal. Lo acusa de trolear sistemáticamente.' },
      { who: 'Javier', type: '🔥 Máxima tensión', desc: '"Pura paja Javier. Hablas por fastidiar."' },
      { who: 'Jesús', type: '🤝 Respeto', desc: 'Lo cita como autoridad: "cuando Jesús interviene, tira factos".' },
    ],
    arc: 'Constante a lo largo del año. Su frustración con Javier crece progresivamente. En dic 2025 sus argumentos se vuelven más elaborados y filosóficos (caso Negreira).',
  },
  {
    id: 'gustavo',
    name: 'Gustavo Torres',
    initials: 'GT',
    nickname: '"Guguito"',
    role: 'El Abogado del Diablo',
    roleShort: 'Contrapunto',
    color: 'oklch(68% 0.18 195)',
    colorHex: '#0a9d8f',
    team: 'Barcelona',
    activity: 7,
    warning: false,
    scores: [
      { label: 'Agresión', val: 3, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 6, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 9, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 9, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'El único barcelonista declarado en un grupo dominado por madridistas',
      'Se retracta públicamente cuando se excede - el más honesto del grupo en eso',
      'Ironía quirúrgica - inocente en forma, letal en fondo',
      'Admite en sep 2025 que el grupo tiene un echo chamber',
    ],
    quotes: [
      { text: '"Ah ok, ¿está ganando el Madrid? ¡Que bien que todo está siendo muy justo!"', ctx: 'Final Copa del Rey, abr 2025' },
      { text: '"Perdón, de nuevo me pasé de tóxico. Retiro ese comentario."', ctx: 'May 2025, autocorrección pública' },
      { text: '"Todos aquí somos jodidos por el algoritmo. Al menos yo lo admito."', ctx: 'Sobre el echo chamber del grupo, sep 2025' },
    ],
    relations: [
      { who: 'Francisco', type: '⚡ Sparring', desc: 'La dinámica más entretenida. Se pican y se ríen.' },
      { who: 'Gabriel', type: '😂 Víctima cómica', desc: 'Regularmente expulsado y readmitido con humor.' },
      { who: 'Javier', type: '🤔 Aliado paradójico', desc: 'Coincide con él accidentalmente - irrita más a Francisco.' },
      { who: 'Jesús', type: '✅ Respeto', desc: 'Debates más tranquilos, reconoce sus argumentos.' },
    ],
    arc: 'Comienza el año muy provocador. Hacia oct-dic 2025 tiene momentos de genuina reflexión. El más evolucionado del grupo en apertura.',
  },
  {
    id: 'jesus',
    name: 'Jesús Burgos',
    initials: 'JB',
    nickname: '"Jesús Ignacio"',
    role: 'El Árbitro Invisible',
    roleShort: 'El Analítico',
    color: 'oklch(70% 0.16 145)',
    colorHex: '#2da860',
    team: 'Real Madrid',
    activity: 6,
    warning: false,
    scores: [
      { label: 'Agresión', val: 2, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 9, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 9, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 8, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Cuando habla, la conversación cambia - sus argumentos son los más escuchados',
      'El sticker como veredicto definitivo: vale más que un párrafo',
      'Humor oscuro y certero que todo el grupo celebra',
      'El compass moral: condena el racismo con naturalidad cuando el grupo lo silencia',
    ],
    quotes: [
      { text: '"Lo de el hate a Vinicius es de estudio."', ctx: 'Feb 2026, incidente Prestiani' },
      { text: '"Solo Francisco hace un comentario así antes de que su avión despegue. 😂"', ctx: 'Reacción a un comentario extremo de Francisco' },
      { text: '"Trato de no opinar ya de los árbitros. Pero es descarado."', ctx: 'Dic 2025 - autocontención con punch final' },
    ],
    relations: [
      { who: 'Francisco', type: '🤝 Respeto mutuo', desc: 'Francisco lo cita como autoridad en el grupo.' },
      { who: 'Gabriel', type: '🤫 Complicidad', desc: 'Silencio cómplice y humor compartido.' },
      { who: 'Javier', type: '😒 Veredicto frío', desc: 'Responde con el sticker 😒 - el juicio más lapidario del grupo.' },
      { who: 'Gustavo', type: '✅ Debate limpio', desc: 'Debates más calmados que con otros miembros.' },
    ],
    arc: 'Consistente y estable todo el año. Su credibilidad crece. En dic 2025 decide "no opinar más de los árbitros" - pero añade el punch. El miembro con mayor inteligencia social del grupo.',
  },
  {
    id: 'javier',
    name: 'Javier Gimenez',
    initials: 'JG',
    nickname: '"Javito"',
    role: 'La Manzana Podrida',
    roleSoft: 'El Provocador',
    roleShort: '⚠ Alerta',
    color: 'oklch(60% 0.25 15)',
    colorHex: '#cc2200',
    team: 'Sin equipo fijo',
    activity: 5,
    warning: true,
    scores: [
      { label: 'Agresión', val: 8, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 2, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 3, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura al diálogo', val: 1, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Borra sus propios mensajes constantemente - múltiples veces por semana',
      'Argumentos circulares: vuelve al mismo punto ignorando lo que le respondiste',
      'Condescendente: "creo que entiendo más de fútbol que varios acá"',
      'Pasivo-agresivo: amenaza con salirse del grupo y luego dice que era broma',
      'Minimizó el racismo: justificó que llamaran "mono" a Vinicius en feb 2026',
      'Cambia la descripción del grupo sin consenso en plenos debates tensos',
    ],
    quotes: [
      { text: '"Capaz para los argentinos decirle mono no tiene connotación racista. A lo mejor le dijo que se deje de comportarse como mono."', ctx: '23 feb 2026 - Gabriel respondió: "¿Es en serio que estamos teniendo esta discusión?"' },
      { text: '"Creo que veo fútbol y entiendo un poquito más que varios acá. Y seguramente jugando también."', ctx: 'May 2025 - condescendencia argumentativa directa' },
      { text: '"Creo que es menos grave discriminar por orientación sexual que por origen étnico."', ctx: '18 feb 2026 - creando una jerarquía de discriminaciones para minimizar el caso' },
      { text: '"Por cierto debería salirme de este grupo antes de que Gabriel llore de nuevo."', ctx: 'May 2025 - inmediatamente cambia la descripción del grupo' },
    ],
    relations: [
      { who: 'Francisco', type: '🔥 Máxima tensión', desc: '"Pura paja Javier. Hablas por fastidiar." - el más afectado por su estilo argumentativo.' },
      { who: 'Gabriel', type: '⚡ Poder admin', desc: 'Fue expulsado del grupo durante la final de Copa del Rey sin aviso.' },
      { who: 'Gustavo', type: '🤔 Paradoja', desc: 'Aliado involuntario. Cuando coinciden, Francisco explota más.' },
      { who: 'Jesús', type: '😒 El veredicto', desc: 'Jesús lo silencia con un sticker - el juicio más definitivo del grupo.' },
    ],
    arc: 'Constante en sus patrones negativos. Alcanza su punto más grave en feb 2026 minimizando el racismo contra Vinicius durante el incidente Benfica. El propio Francisco lo identifica como el miembro que habría que "sacar del echo chamber".',
  },
  {
    id: 'luis',
    name: 'Luís Torrado',
    initials: 'LT',
    nickname: '"Torradinchis"',
    role: 'El Corresponsal',
    roleShort: 'Corresponsal',
    color: 'oklch(65% 0.16 260)',
    colorHex: '#3f5cc4',
    team: 'Real Madrid',
    activity: 3,
    warning: false,
    scores: [
      { label: 'Agresión', val: 2, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 7, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 6, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 8, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Participación ocasional pero siempre oportuna y bien fundamentada',
      'Aporta perspectiva desde España - ve el fútbol europeo de primera mano',
      'Sus entradas suelen bajar la temperatura del debate',
      'Tono directo y venezolano sin pretensiones filosóficas',
    ],
    quotes: [
      { text: '"Marico no bajo a defender ni él ni Mbappe con 9 jugadores el último tiro libre."', ctx: 'Champions, ene 2026' },
      { text: '"No marico, confundes las cosas. Ser canchero es diferente a que te estén diciendo vainas todo el tiempo."', ctx: 'Debate racismo vs. picardía, feb 2026' },
    ],
    relations: [
      { who: 'Francisco', type: '✅ Aliado técnico', desc: 'Coinciden en análisis del fútbol europeo.' },
      { who: 'Gabriel', type: '✅ Complicidad', desc: 'Visión compartida, ambos desde España.' },
      { who: 'Grupo', type: '🧊 Moderador natural', desc: 'Su entrada suele calmar los debates.' },
    ],
    arc: 'Consistente. Participa más cuando tiene contexto de primera mano desde España. Su comentario durante el debate de Vinicius/Prestiani fue uno de los más equilibrados.',
  },
  {
    id: 'andres',
    name: 'Andrés Eduardo Pinto',
    initials: 'AP',
    nickname: '"Pintin"',
    role: 'El Pacifista',
    roleShort: 'Pacifista',
    color: 'oklch(65% 0.15 90)',
    colorHex: '#7a9a10',
    team: 'Atlético de Madrid',
    activity: 3,
    warning: false,
    scores: [
      { label: 'Agresión', val: 1, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 8, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 7, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 9, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'El miembro más tranquilo - raramente entra en conflictos directos',
      'Fan del Atlético: la rareza en un grupo dominado por madridistas',
      'Ha querido salirse del grupo "5567 veces" por la toxicidad acumulada',
      'Su ausencia en los debates más tensos es en sí misma un mensaje',
    ],
    quotes: [
      { text: '"Que tóxico este grupo."', ctx: 'Mayo 2025 - reacción directa a uno de los debates' },
      { text: '"Me he querido salir 5567 veces. Jajajaja."', ctx: 'Uno de sus mensajes más recordados' },
      { text: '"Un padre responsable." - sobre por qué no participa más', ctx: 'Con humor sobre sus ausencias estratégicas' },
    ],
    relations: [
      { who: 'Grupo', type: '🕊️ Ancla', desc: 'Su presencia tranquila equilibra la toxicidad colectiva.' },
      { who: 'Francisco', type: '😄 Víctima cómica', desc: 'Blanco ocasional de sus bromas afectuosas.' },
    ],
    arc: 'Consistente y pacificador todo el año. Participa menos cuando los debates se vuelven más tóxicos - su versión discreta de protestar.',
  },
  {
    id: 'gerardo',
    name: 'Gerardo Vitale Errico',
    initials: 'GE',
    nickname: 'Gerardo',
    role: 'El Filósofo',
    roleShort: 'Filósofo',
    color: 'oklch(70% 0.18 52)',
    colorHex: '#c07a00',
    team: 'Neutral / Italia',
    activity: 3,
    warning: false,
    scores: [
      { label: 'Agresión', val: 3, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 7, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 7, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 8, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Aparece en debates de principios - libertad de expresión, privacidad, ética',
      'Sus argumentos sorprenden con perspectivas que nadie anticipó',
      'Llega tarde a conversaciones y lo admite con humor',
      'Perspectiva ítalo-venezolana única en el grupo',
    ],
    quotes: [
      { text: '"Aquí tirando un comentario sin saber de qué coño están hablando 😂"', ctx: 'Debate Prestiani/Vinicius, feb 2026' },
      { text: '"Me parece peligroso que una acusación verbal pueda parar partidos."', ctx: 'Debate privacidad vs. anti-racismo, feb 2026' },
      { text: '"Siento la necesidad de enviar una nota de voz."', ctx: 'Cuando el debate se pone filosófico' },
    ],
    relations: [
      { who: 'Francisco', type: '⚡ Debate filosófico', desc: 'Uno de sus debates más interesantes sobre privacidad y libre expresión.' },
      { who: 'Grupo', type: '🔭 Perspectiva única', desc: 'Aporta ángulos que nadie más plantea en el grupo.' },
    ],
    arc: 'Aparece más en 2026. El caso Prestiani/Vinicius fue su participación más notable. Su postura generó uno de los debates más inesperados del período analizado.',
  },
  {
    id: 'espana34',
    name: 'Contacto España (+34)',
    shortName: 'España',
    initials: '+34',
    nickname: '"El +34"',
    role: 'El Refuerzo Peninsular',
    roleShort: 'Refuerzo',
    color: 'oklch(72% 0.18 335)',
    colorHex: '#cb4b8d',
    team: 'Real Madrid',
    activity: 4,
    warning: false,
    scores: [
      { label: 'Agresión', val: 3, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 7, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 6, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 7, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Entra desde España con tono relajado, madridista y bastante integrado al humor local',
      'Aporta comentarios de fantasy, fichajes y vida futbolera en Madrid sin monopolizar la discusión',
      'Suele responder con emojis y frases cortas - participa más como refuerzo constante que como polemista principal',
      'En el material fuente su contacto no está guardado con nombre, así que aquí queda anonimizado como "El +34"',
    ],
    quotes: [
      { text: '"Con esa rueda de prensa claramente ya no hay neutralidad en los árbitros."', ctx: 'Abr 2025 - entra alineado con la desconfianza arbitral del núcleo madridista' },
      { text: '"Si el Barça fuera un partido político claramente sería el PSOE."', ctx: 'Jun 2025 - humor político aplicado al anti-barcelonismo del grupo' },
      { text: '"Aquí la gente no da leñazos y no te lesionan, todo friendly."', ctx: 'Dic 2025 - invitando a jugar fútbol en Madrid' },
    ],
    relations: [
      { who: 'Francisco', type: '🤝 Complicidad ibérica', desc: 'Conecta con él desde España y termina extendiendo el vínculo al fútbol presencial.' },
      { who: 'Gabriel', type: '😄 Humor compartido', desc: 'Gabriel lo usa como espejo cómico: "tú y Francisco son la misma mierda".' },
      { who: 'Gerardo', type: '⚽ Plan deportivo', desc: 'Lo incluye en propuestas de jugar juntos; la relación parece más práctica que ideológica.' },
      { who: 'Grupo', type: '✅ Refuerzo estable', desc: 'No domina la conversación, pero cuando aparece suma tono y continuidad.' },
    ],
    arc: 'Empieza como presencia lateral en primavera de 2025 y gana sitio hacia el ciclo de fantasy y fútbol presencial en Madrid. Nunca se vuelve protagonista, pero sí una pieza estable del ecosistema social del grupo.',
  },
  {
    id: 'jorge',
    name: 'Jorge Anzola',
    shortName: 'Jorge',
    initials: 'JA',
    nickname: '"El Terror de Amsterdam"',
    role: 'El Refuerzo Caótico',
    roleShort: 'Caótico',
    color: 'oklch(76% 0.16 310)',
    colorHex: '#b766d4',
    team: 'Messi-safe / multi-liga',
    activity: 2,
    warning: false,
    scores: [
      { label: 'Agresión', val: 4, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 7, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 8, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 8, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Entra tarde, recibe contexto acelerado y entiende rápido el código interno del grupo',
      'Su humor es absurdo y autoparódico - convierte el desconcierto en personaje',
      'Aporta side quests: F1, fantasy y comentarios dramáticos más que litigios interminables sobre árbitros',
      'Se integra más por química social que por volumen de mensajes',
    ],
    quotes: [
      { text: '"Nunca hablaría mal de Messi. No quiero tener peos con Infantino…"', ctx: 'Ago 2025 - se adapta al principal tabú del grupo desde su primer día' },
      { text: '"I’m already overwhelmed, no puedo poner a 11 CR"', ctx: 'Sep 2025 - entrando al fantasy con caos y honestidad' },
      { text: '"Perdimos el mundial de desayunos"', ctx: 'Sep 2025 - ejemplo perfecto de su dramatismo humorístico' },
    ],
    relations: [
      { who: 'Francisco', type: '😄 Bienvenida performática', desc: 'Francisco lo introduce con narrativa épica y Jorge responde siguiendo el juego.' },
      { who: 'Aaron', type: '🤯 Caos familiar', desc: 'La conversación sobre parentescos se convierte en una mini-comedia propia.' },
      { who: 'Gustavo', type: '📚 Contexto guiado', desc: 'Gustavo le da "material previo" para entender la locura del grupo.' },
      { who: 'Jesús', type: '😂 Validación instantánea', desc: 'Jesús suele comprar el chiste rápido y lo integra al tono colectivo.' },
    ],
    arc: 'Su debut en agosto de 2025 es tardío pero exitoso. No llega a ser central en las discusiones grandes, aunque sí refresca el grupo con humor lateral y una energía menos doctrinaria.',
  },
  {
    id: 'aaron',
    name: 'Aaron Rodrigues',
    shortName: 'Aaron',
    initials: 'AR',
    nickname: '"El cuñado (por ahora)"',
    role: 'El Rookie Aplicado',
    roleShort: 'Rookie',
    color: 'oklch(77% 0.15 250)',
    colorHex: '#6b82de',
    team: 'CD Tenerife',
    activity: 4,
    warning: false,
    scores: [
      { label: 'Agresión', val: 3, color: 'oklch(62% 0.22 25)' },
      { label: 'Colaboración', val: 8, color: 'oklch(70% 0.16 145)' },
      { label: 'Humor', val: 7, color: 'oklch(72% 0.18 60)' },
      { label: 'Apertura', val: 8, color: 'oklch(68% 0.18 200)' },
    ],
    patterns: [
      'Entra como nuevo cuñado de Francisco y se integra rápido sin ponerse a la defensiva',
      'Aprende el fantasy en tiempo real, pregunta reglas y enseguida empieza a competir de verdad',
      'Corrige identidades futboleras - "no es Las Palmas, es Tenerife" - y marca territorio sin volverse pesado',
      'Usa ChatGPT, estadísticas y memes para ponerse al día con sorprendente velocidad',
    ],
    quotes: [
      { text: '"A mi me invitaron para hacerme bullying por lo que veo"', ctx: 'Sep 2025 - lectura correcta de la cultura de ingreso al grupo' },
      { text: '"En realidad es el club deportivo Tenerife, si los confundes aquí te metes en un problema"', ctx: 'Sep 2025 - fijando identidad propia desde el primer día' },
      { text: '"Ya estoy buscando stats en chat gpt"', ctx: 'Sep 2025 - rookie, sí; pasivo, no' },
    ],
    relations: [
      { who: 'Francisco', type: '🤝 Tutoría familiar', desc: 'Francisco lo presenta, lo provoca y a la vez le abre la puerta de entrada.' },
      { who: 'Jesús', type: '😄 Complicidad física', desc: 'El bullying de bienvenida con Jesús se vuelve parte de su integración.' },
      { who: 'Jorge', type: '😂 Enredo genealógico', desc: 'Su conexión con Jorge arranca con una discusión delirante sobre grados de cuñadez.' },
      { who: 'Grupo', type: '✅ Adaptación veloz', desc: 'Pasa de "soy nuevo" a competir y opinar con naturalidad en muy poco tiempo.' },
    ],
    arc: 'Aparece en septiembre de 2025 como incorporación tardía, pero enseguida deja de sonar a invitado. El fantasy acelera su integración y termina siendo de los nuevos que más rápido entienden la lógica emocional del grupo.',
  },
]

export const EDGES = [
  { from: 'francisco', to: 'gabriel', type: 'ally', label: 'Alianza principal' },
  { from: 'francisco', to: 'jesus', type: 'ally', label: 'Respeto mutuo' },
  { from: 'francisco', to: 'gustavo', type: 'tension', label: 'Conflicto central' },
  { from: 'francisco', to: 'javier', type: 'high-tension', label: 'Máxima frustración' },
  { from: 'gabriel', to: 'jesus', type: 'ally', label: 'Complicidad silenciosa' },
  { from: 'gabriel', to: 'gustavo', type: 'comic', label: 'Expulsiones rituales' },
  { from: 'gabriel', to: 'javier', type: 'tension', label: 'Lo expulsó en Copa del Rey' },
  { from: 'gustavo', to: 'jesus', type: 'neutral', label: 'Debates respetuosos' },
  { from: 'gustavo', to: 'javier', type: 'ambiguous', label: 'Aliado involuntario' },
  { from: 'jesus', to: 'javier', type: 'cold', label: '😒 El veredicto' },
  { from: 'francisco', to: 'luis', type: 'neutral', label: 'Análisis técnico' },
  { from: 'francisco', to: 'andres', type: 'neutral', label: 'Amistad tranquila' },
  { from: 'francisco', to: 'gerardo', type: 'ambiguous', label: 'Debate de principios' },
  { from: 'francisco', to: 'espana34', type: 'ally', label: 'Madrid desde España' },
  { from: 'gabriel', to: 'espana34', type: 'comic', label: 'Humor compartido' },
  { from: 'gerardo', to: 'espana34', type: 'neutral', label: 'Planes de jugar en Madrid' },
  { from: 'francisco', to: 'jorge', type: 'comic', label: 'Bienvenida performática' },
  { from: 'gustavo', to: 'jorge', type: 'neutral', label: 'Le pasó el contexto' },
  { from: 'aaron', to: 'jorge', type: 'comic', label: 'Caos familiar' },
  { from: 'francisco', to: 'aaron', type: 'ally', label: 'Tutoría del rookie' },
  { from: 'jesus', to: 'aaron', type: 'neutral', label: 'Bullying de bienvenida' },
]

export const NODE_POS = {
  gabriel: { x: 540, y: 110 },
  francisco: { x: 220, y: 330 },
  gustavo: { x: 850, y: 210 },
  jesus: { x: 430, y: 530 },
  javier: { x: 780, y: 560 },
  luis: { x: 110, y: 560 },
  andres: { x: 590, y: 690 },
  gerardo: { x: 1060, y: 430 },
  espana34: { x: 980, y: 110 },
  jorge: { x: 1060, y: 650 },
  aaron: { x: 230, y: 690 },
}

export const EDGE_STYLE = {
  ally: { stroke: 'oklch(70% 0.16 145)', w: 3, dash: '', op: 0.7 },
  tension: { stroke: 'oklch(62% 0.22 25)', w: 2.5, dash: '', op: 0.7 },
  'high-tension': { stroke: 'oklch(62% 0.22 25)', w: 4.5, dash: '', op: 0.9 },
  comic: { stroke: 'oklch(72% 0.18 60)', w: 2, dash: '8,4', op: 0.7 },
  neutral: { stroke: 'rgba(255,255,255,0.22)', w: 1.5, dash: '', op: 0.5 },
  ambiguous: { stroke: 'oklch(68% 0.18 200)', w: 2, dash: '5,3', op: 0.6 },
  cold: { stroke: 'rgba(255,255,255,0.12)', w: 1, dash: '3,3', op: 0.4 },
}
